'use strict';
const $=s=>document.querySelector(s), canvas=$('#board'), ctx=canvas.getContext('2d');
const W=900, CX=450, CY=450, R=350, POCKETS=[[38,38],[862,38],[38,862],[862,862]], PR=34;
const COLORS={gold:'#f6c84f',gold2:'#ffe07a',teal:'#31e1cb',red:'#ff5362',cream:'#f7ead0',black:'#1e2630'};
let mode='ai',players=[],turn=0,coins=[],striker=null,drag=null,shot=false,looping=false,last=0,timer=20,timerId=null,gameOver=false,sound=true,audio=null,particles=[],stats=JSON.parse(localStorage.getItem('carromClashStats')||'{"games":0,"wins":0}');
function playerTemplate(name,color){return{name,color,score:0,fouls:0,shots:0,queen:0,pocketed:0}}
function initPlayers(){players=mode==='4p'?[['Player 1','#f6c84f'],['Player 2','#31e1cb'],['Player 3','#ff5362'],['Player 4','#b98cff']].map(x=>playerTemplate(x[0],x[1])):[playerTemplate('Player 1','#f6c84f'),playerTemplate(mode==='ai'?'Computer':'Player 2','#31e1cb')];}
function unlockAudio(){if(!sound)return;if(!audio){try{audio=new(window.AudioContext||window.webkitAudioContext)()}catch(e){audio=null}}if(audio?.state==='suspended')audio.resume()}
function tone(freq=440,d=.07,type='sine',gain=.035){if(!sound)return;unlockAudio();if(!audio)return;const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime;o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(gain,t+.008);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(g);g.connect(audio.destination);o.start(t);o.stop(t+d+.02)}
const sfx={click:()=>tone(560,.045,'triangle',.025),hit:(v=1)=>tone(150+Math.min(180,v*30),.055,'square',.018),rail:()=>tone(105,.06,'triangle',.025),pocket:()=>{tone(620,.08,'sine',.04);setTimeout(()=>tone(900,.12,'sine',.03),60)},queen:()=>{tone(520,.1,'triangle',.05);setTimeout(()=>tone(780,.12,'triangle',.045),70);setTimeout(()=>tone(1040,.14,'triangle',.035),150)},foul:()=>{tone(150,.13,'sawtooth',.04);setTimeout(()=>tone(100,.16,'sawtooth',.03),90)},win:()=>[523,659,784,1047,1319].forEach((n,i)=>setTimeout(()=>tone(n,.18,'triangle',.05),i*90))};
function piece(x,y,r,color,type='coin'){return{x,y,r,color,type,vx:0,vy:0,pocketed:false}}
function setup(){stopLoop();clearInterval(timerId);particles=[];coins=[];shot=false;gameOver=false;drag=null;striker=null;let ring=[...Array(6)].map((_,i)=>i);coins.push(piece(CX,CY,12,COLORS.red,'queen'));for(let rr=1;rr<=2;rr++)for(const i of [...Array(rr*6)].map((_,i)=>i)){const a=i*Math.PI*2/(rr*6)+(rr===2?.12:0);coins.push(piece(CX+Math.cos(a)*26*rr,CY+Math.sin(a)*26*rr,11,rr%2?COLORS.cream:COLORS.black))}for(let i=0;i<6;i++){const a=i*Math.PI/3;coins.push(piece(CX+Math.cos(a)*62,CY+Math.sin(a)*62,11,i%2?COLORS.cream:COLORS.black))}turn=0;updateHud();feed('Break shot ready. Aim directly through the center.');setTimer();draw();pulse('READY',COLORS.teal)}
function start(m){unlockAudio();sfx.click();mode=m;initPlayers();$('#home').classList.remove('active');$('#game').classList.add('active');setup()}
function reset(){unlockAudio();sfx.click();setup()}
function stopLoop(){looping=false;last=0}
function startLoop(){if(looping)return;looping=true;last=0;requestAnimationFrame(loop)}
function loop(ts){if(!looping)return;if(!last)last=ts;const dt=Math.min(2.2,(ts-last)/16.67);last=ts;physics(dt);draw();if(looping&&(shot||moving()||particles.length))requestAnimationFrame(loop);else stopLoop()}
function active(){return coins.filter(o=>!o.pocketed)}
function moving(){return active().some(o=>Math.hypot(o.vx,o.vy)>.035)||(striker&&Math.hypot(striker.vx,striker.vy)>.035)}
function setTimer(){clearInterval(timerId);timer=20;renderTimer();timerId=setInterval(()=>{if(gameOver||shot)return;timer--;renderTimer();if(timer<=0){players[turn].fouls++;sfx.foul();feed(players[turn].name+' timed out.');pulse('TIME OUT',COLORS.red);finishTurn(false)}},1000)}
function renderTimer(){$('#timer').textContent=timer;$('#timerBar').style.width=(timer/20*100)+'%';$('#timerBar').classList.toggle('danger',timer<=5)}
function updateHud(){const p=players[turn],p1=players[0],p2=players[1];$('#turnName').textContent=p?.name||'';$('#status').textContent=mode==='ai'&&turn===1?'Computer is thinking…':'Aim and shoot';$('#turnDot').style.background=p?.color||COLORS.gold;$('#turnDot').style.boxShadow=`0 0 18px ${p?.color||COLORS.gold}`;$('#p1Score').textContent=p1?.score||0;$('#p2Score').textContent=p2?.score||0;$('#p1Name').textContent=p1?.name||'';$('#p2Name').textContent=p2?.name||'';$('#p1Meta').textContent=p1?`${p1.score} points · ${p1.fouls} fouls`:'';$('#p2Meta').textContent=p2?`${p2.score} points · ${p2.fouls} fouls`:'';$('#p1Avatar').textContent='P1';$('#p2Avatar').textContent=mode==='ai'?'AI':'P2'}
function feed(text){const e=document.createElement('div');e.textContent='› '+text;$('#feedList').prepend(e);while($('#feedList').children.length>9)$('#feedList').lastChild.remove()}
function pulse(text,color=COLORS.gold){const e=document.createElement('div');e.className='fx-text';e.textContent=text;e.style.color=color;$('#fxLayer').appendChild(e);setTimeout(()=>e.remove(),850)}
function toast(text){const e=$('#toast');e.textContent=text;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1100)}
function burst(x,y,n=12){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,v=1.5+Math.random()*4;particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:1,size:2+Math.random()*4})}startLoop()}
function confetti(){for(let i=0;i<75;i++){const e=document.createElement('i');e.className='confetti';e.style.background=[COLORS.gold,COLORS.teal,COLORS.red,'#b98cff'][i%4];e.style.setProperty('--x',(Math.random()*600-300));e.style.setProperty('--y',(Math.random()*650+100));e.style.transform=`translate(-50%,0)`;e.style.left=(50+Math.random()*6-3)+'%';e.style.top=(38+Math.random()*5)+'%';$('#fxLayer').appendChild(e);setTimeout(()=>e.remove(),1500)}}
function strikerPos(){if(players.length===4){const side=turn%4;if(side===0)return[CX,CY+245];if(side===1)return[CX+245,CY];if(side===2)return[CX,CY-245];return[CX-245,CY]}return[CX,CY+245]}
function placeStriker(){const [x,y]=strikerPos();striker={x,y,r:18,vx:0,vy:0,color:COLORS.gold,pocketed:false}}
function canPlay(){return !gameOver&&!shot&&!(mode==='ai'&&turn===1)}
function pointer(e){const r=canvas.getBoundingClientRect();return{x:Math.max(0,Math.min(W,(e.clientX-r.left)*W/r.width)),y:Math.max(0,Math.min(W,(e.clientY-r.top)*W/r.height))}}
function shoot(target){if(!striker)return;const dx=target.x-striker.x,dy=target.y-striker.y,len=Math.hypot(dx,dy);if(len<14){drag=null;setPower(0);return}const p=Math.min(18,Math.max(4,len/10));striker.vx=dx/len*p;striker.vy=dy/len*p;players[turn].shots++;shot=true;$('#status').textContent=players[turn].name+' shot in progress';feed(players[turn].name+' fired.');sfx.hit(p);setPower(0);startLoop()}
function finishTurn(scored){if(gameOver)return;shot=false;if(striker?.pocketed){players[turn].fouls++;sfx.foul();feed(players[turn].name+' fouled: striker pocketed.');pulse('FOUL',COLORS.red)}else if(scored){feed(players[turn].name+' keeps the turn.');pulse('KEEP TURN',players[turn].color)}else turn=(turn+1)%players.length;placeStriker();updateHud();setTimer();draw();if(mode==='ai'&&turn===1)setTimeout(aiShot,550)}
function aiShot(){if(!canPlay()||mode!=='ai'||turn!==1)return;const targets=active().filter(o=>o.type==='coin'||o.type==='queen');if(!targets.length){finishGame();return}const [sx,sy]=strikerPos();let best=targets[0],bestScore=1e9;for(const t of targets){const d=Math.hypot(t.x-sx,t.y-sy);if(d<bestScore){bestScore=d;best=t}}const angle=Math.atan2(best.y-sy,best.x-sx)+(Math.random()-.5)*.12;const dist=Math.min(175,bestScore*.8+80);striker={x:sx,y:sy,r:18,vx:Math.cos(angle)*Math.min(15,dist/12),vy:Math.sin(angle)*Math.min(15,dist/12),color:COLORS.gold,pocketed:false};players[turn].shots++;shot=true;$('#status').textContent='Computer shot in progress';feed('Computer fired.');sfx.hit(8);startLoop()}
function pocketAt(x,y){return POCKETS.some(([px,py])=>Math.hypot(x-px,y-py)<PR)}
function pocketCoin(o){if(o.pocketed)return;o.pocketed=true;o.vx=o.vy=0;if(o.type==='queen'){players[turn].score+=3;players[turn].queen++;sfx.queen();burst(o.x,o.y,30);pulse('QUEEN!',COLORS.red);feed(players[turn].name+' pocketed the Queen +3')}else{players[turn].score++;players[turn].pocketed++;sfx.pocket();burst(o.x,o.y,12);pulse('+1',COLORS.gold);feed(players[turn].name+' pocketed a coin +1')}updateHud()}
function updateObj(o,dt,isStriker=false){if(Math.hypot(o.vx,o.vy)<.001){o.vx=o.vy=0;return}o.x+=o.vx*dt;o.y+=o.vy*dt;const f=Math.pow(.983,dt*60);o.vx*=f;o.vy*=f;if(pocketAt(o.x,o.y)){o.pocketed=true;o.vx=o.vy=0;if(isStriker){sfx.foul();pulse('FOUL',COLORS.red)}else pocketCoin(o);return}const dx=o.x-CX,dy=o.y-CY,d=Math.hypot(dx,dy),limit=R-o.r;if(d>limit){const nx=dx/(d||1),ny=dy/(d||1),dot=o.vx*nx+o.vy*ny;o.vx-=2*dot*nx;o.vy-=2*dot*ny;o.x=CX+nx*limit;o.y=CY+ny*limit;o.vx*=.91;o.vy*=.91;sfx.rail()}}
function collide(a,b){if(!a||!b||a.pocketed||b.pocketed)return false;const dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy),min=a.r+b.r;if(d<=0||d>=min)return false;const nx=dx/d,ny=dy/d,over=min-d;a.x-=nx*over/2;a.y-=ny*over/2;b.x+=nx*over/2;b.y+=ny*over/2;const rel=(a.vx-b.vx)*nx+(a.vy-b.vy)*ny;if(rel<=0)return false;const impulse=rel*.96;a.vx-=impulse*nx;a.vy-=impulse*ny;b.vx+=impulse*nx;b.vy+=impulse*ny;sfx.hit(Math.min(10,rel));return true}
function physics(dt){if(striker&&!striker.pocketed)updateObj(striker,dt,true);for(const o of active())updateObj(o,dt,false);const all=striker&&!striker.pocketed?[striker,...active()]:active();for(let i=0;i<all.length;i++)for(let j=i+1;j<all.length;j++)collide(all[i],all[j]);for(const p of particles){p.x+=p.vx;p.y+=p.vy;p.vy+=.04;p.vx*=.985;p.life-=.022}particles=particles.filter(p=>p.life>0);if(shot&&!moving()){const scored=players[turn].pocketed>0;coins=coins.filter(o=>!o.pocketed);if(coins.filter(o=>o.type==='coin').length===0)finishGame();else finishTurn(scored)}}
function finishGame(){if(gameOver)return;gameOver=true;clearInterval(timerId);coins=coins.filter(o=>!o.pocketed);const winner=players.reduce((a,b)=>b.score>a.score?b:a,players[0]);stats.games++;if(mode==='ai'&&winner===players[0])stats.wins++;localStorage.setItem('carromClashStats',JSON.stringify(stats));sfx.win();burst(CX,CY,70);confetti();showWinner(winner)}
function showWinner(w){$('#modalBody').innerHTML=`<div class="winner-card"><div class="winner-kicker">MATCH COMPLETE · SEASON 01</div><h2>🏆 ${w.name.toUpperCase()} WINS!</h2><p class="winner-score">${w.score}<span> POINTS</span></p><div class="winner-stats"><span>${w.shots}<b>SHOTS</b></span><span>${w.fouls}<b>FOULS</b></span><span>${w.queen}<b>QUEEN</b></span></div><button class="winner-btn" id="rematchBtn">⚡ PLAY AGAIN</button></div>`;$('#modal').classList.remove('hidden');$('#rematchBtn').onclick=()=>{closeModal();reset()};pulse('VICTORY',COLORS.gold2)}
function draw(){ctx.clearRect(0,0,W,W);const bg=ctx.createRadialGradient(CX,CY,40,CX,CY,560);bg.addColorStop(0,'#152b40');bg.addColorStop(1,'#06111d');ctx.fillStyle=bg;ctx.fillRect(0,0,W,W);drawBoard();for(const o of coins)if(!o.pocketed)drawCoin(o);if(striker&&!striker.pocketed)drawStriker();for(const p of particles){ctx.save();ctx.globalAlpha=p.life;ctx.fillStyle=p.life>.5?COLORS.gold:COLORS.teal;ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,Math.PI*2);ctx.fill();ctx.restore()}}
function drawBoard(){ctx.save();ctx.translate(CX,CY);ctx.shadowColor='#000b';ctx.shadowBlur=38;const outer=ctx.createRadialGradient(-100,-110,60,0,0,430);outer.addColorStop(0,'#f7dca5');outer.addColorStop(.65,'#c68d4a');outer.addColorStop(1,'#744421');ctx.fillStyle=outer;ctx.beginPath();ctx.arc(0,0,415,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;const inner=ctx.createRadialGradient(-70,-80,40,0,0,380);inner.addColorStop(0,'#f8dda8');inner.addColorStop(1,'#e5bc72');ctx.fillStyle=inner;ctx.beginPath();ctx.arc(0,0,R+13,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#704626';ctx.lineWidth=8;ctx.beginPath();ctx.arc(0,0,R,0,Math.PI*2);ctx.stroke();ctx.strokeStyle='#a56d37';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,92,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.arc(0,0,43,0,Math.PI*2);ctx.stroke();for(const y of [-190,190]){ctx.beginPath();ctx.moveTo(-245,y);ctx.lineTo(245,y);ctx.stroke()}for(const x of [-190,190]){ctx.beginPath();ctx.moveTo(x,-245);ctx.lineTo(x,245);ctx.stroke()}ctx.restore();for(const [x,y] of POCKETS){const g=ctx.createRadialGradient(x-6,y-6,3,x,y,PR);g.addColorStop(0,'#000');g.addColorStop(.72,'#0b1016');g.addColorStop(1,'#5a331d');ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,PR,0,Math.PI*2);ctx.fill()}}
function drawCoin(o){ctx.save();ctx.shadowColor='#0008';ctx.shadowBlur=8;const g=ctx.createRadialGradient(o.x-4,o.y-5,2,o.x,o.y,o.r);if(o.type==='queen'){g.addColorStop(0,'#ffb1b7');g.addColorStop(.4,COLORS.red);g.addColorStop(1,'#a72839')}else if(o.color===COLORS.black){g.addColorStop(0,'#4a535f');g.addColorStop(1,'#141a21')}else{g.addColorStop(0,'#fff6dc');g.addColorStop(1,'#d6c39b')}ctx.fillStyle=g;ctx.beginPath();ctx.arc(o.x,o.y,o.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle=o.type==='queen'?COLORS.gold2:'#88795e';ctx.lineWidth=2;ctx.stroke();if(o.type==='queen'){ctx.strokeStyle='#ffe7a0';ctx.lineWidth=2;ctx.beginPath();ctx.arc(o.x,o.y,o.r*.47,0,Math.PI*2);ctx.stroke()}ctx.restore()}
function drawStriker(){const s=striker||{x:strikerPos()[0],y:strikerPos()[1],r:18};ctx.save();const g=ctx.createRadialGradient(s.x-5,s.y-6,2,s.x,s.y,21);g.addColorStop(0,'#fff6c9');g.addColorStop(.45,COLORS.gold);g.addColorStop(1,'#8e5b27');ctx.fillStyle=g;ctx.shadowColor=COLORS.gold;ctx.shadowBlur=drag?24:12;ctx.beginPath();ctx.arc(s.x,s.y,18,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='#5d3c22';ctx.lineWidth=2;ctx.stroke();ctx.strokeStyle=COLORS.teal;ctx.lineWidth=3;ctx.globalAlpha=.35;ctx.beginPath();ctx.arc(s.x,s.y,26+Math.sin(Date.now()/180)*3,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1;if(drag){const dx=drag.x-s.x,dy=drag.y-s.y,len=Math.min(520,Math.hypot(dx,dy));const a=Math.atan2(dy,dx);ctx.strokeStyle='rgba(49,225,203,.95)';ctx.lineWidth=3;ctx.setLineDash([10,9]);ctx.beginPath();ctx.moveTo(s.x,s.y);ctx.lineTo(s.x+Math.cos(a)*len,s.y+Math.sin(a)*len);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='rgba(246,200,79,.22)';ctx.beginPath();ctx.moveTo(s.x,s.y);ctx.arc(s.x,s.y,Math.min(170,len),a-.09,a+.09);ctx.closePath();ctx.fill();}ctx.restore()}
function setPower(v){const n=Math.max(0,Math.min(100,v));$('#powerFill').style.width=n+'%';$('#powerValue').textContent=Math.round(n)+'%'}
canvas.addEventListener('pointerdown',e=>{unlockAudio();if(!canPlay())return;const p=pointer(e),[sx,sy]=strikerPos();if(Math.hypot(p.x-sx,p.y-sy)<55){striker={x:sx,y:sy,r:18,vx:0,vy:0,color:COLORS.gold,pocketed:false};drag=p;canvas.setPointerCapture?.(e.pointerId);sfx.click();draw()}});
canvas.addEventListener('pointermove',e=>{if(!drag||!canPlay())return;drag=pointer(e);const[sx,sy]=strikerPos();const len=Math.hypot(drag.x-sx,drag.y-sy);setPower(Math.min(100,len/2.4));draw()});
canvas.addEventListener('pointerup',e=>{if(!drag)return;const p=pointer(e);shoot(p);drag=null;draw()});canvas.addEventListener('pointercancel',()=>{drag=null;setPower(0);draw()});
$('#soundBtn').onclick=()=>{sound=!sound;$('#soundBtn').textContent=sound?'🔊':'🔇';if(sound){unlockAudio();sfx.click()}else if(audio)audio.suspend()};
$('#helpBtn').onclick=()=>{unlockAudio();sfx.click();$('#modalBody').innerHTML='<h2>How to play</h2><p>Touch the glowing striker, drag <b>toward the target</b>, then release. The dotted guide is the exact shot direction.</p><ul><li>Longer drag = more power.</li><li>Pocket a coin to score +1.</li><li>Queen = +3.</li><li>Pocketing the striker is a foul.</li><li>20 seconds per turn.</li><li>In VS Computer, the AI aims automatically.</li></ul><p><b>Center tip:</b> place the striker on the bottom line and drag straight toward the red queen. This version uses intuitive forward aiming, so the shot travels in the same direction as your drag.</p>';$('#modal').classList.remove('hidden')};
$('#closeModal').onclick=closeModal;$('#modal').addEventListener('pointerdown',e=>{if(e.target===$('#modal'))closeModal()});function closeModal(){$('#modal').classList.add('hidden')}
$('#newBtn').onclick=reset;$('#homeBtn').onclick=()=>{clearInterval(timerId);stopLoop();closeModal();$('#game').classList.remove('active');$('#home').classList.add('active');sfx.click()};document.querySelectorAll('.mode-card').forEach(b=>b.addEventListener('click',()=>start(b.dataset.mode)));window.addEventListener('resize',draw);window.addEventListener('orientationchange',()=>setTimeout(draw,120));
initPlayers();placeStriker();draw();
